backend:
  name: git-gateway
  branch: main # Substitua pelo nome do branch principal do repositório

media_folder: "assets" # Onde as imagens serão armazenadas no repositório
public_folder: "/assets/uploads" # Onde as imagens serão acessíveis publicamente

collections:
  - name: "links"
    label: "Links"
    files:
      - file: "content/links.json"
        label: "Links"
        name: "links"
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Tipo", name: "type", widget: "string" } # Tipo do link (Instagram, WhatsApp, etc.)
              - { label: "URL", name: "url", widget: "string" } # URL do link
